# この Dev Container は、typescript-node variant をベースにしている。
# 他の variant とは異なるので注意(typescript-node variant の後にビルドすること)
ARG BASE_REPO="ghcr.io/hankei6km/test-dev-containers-images"
ARG BASE_TAG_SUFFIX="latest"
FROM ${BASE_REPO}:typescript-node_${BASE_TAG_SUFFIX}