name: Build and Push Dev Container Image

on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "!v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create temporary directory in workspace
        run: |
          TEMP_DIR="${GITHUB_WORKSPACE}/tmp/buildx-cache"
          mkdir -m 0700 -p "$TEMP_DIR"
          echo "Temporary directory created: $TEMP_DIR"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/tmp/buildx-cache
          # とりあえずキャッシュのキーはブランチのヘッドにしておく。
          key: ${{ runner.os }}-docker-buildx-${{ github.head_ref }}
          restore-keys: |
            ${{ runner.os }}-docker-buildx

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dev Container CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Build and Push Image
        run: |
          TEMP_DIR="${GITHUB_WORKSPACE}/tmp/buildx-cache"
          CACHE_DIR="${TEMP_DIR}/${VARIANT}"
          BRANCH_NAME="$(echo $GITHUB_HEAD_REF | sed 's|refs/heads/||' | sed 's|[^a-zA-Z0-9._-]|_|g')"
          BRANCH_DATE_TAG="${BRANCH_NAME}-$(date +%Y-%m-%d)"
          test -d "${CACHE_DIR}" || mkdir -p "${CACHE_DIR}"
          ./scripts/image_build.sh \
            --repo "${REPO_NAME}" \
            --tag "${BRANCH_DATE_TAG}" \
            --platform "${PLATFORM}" \
            --push "true" \
            --cache-to "type=local,dest=${CACHE_DIR}" \
            --cache-from "type=local,src=${CACHE_DIR}" \
            --user "${GITHUB_ACTOR}" \
            --is-main-branch "${IS_MAIN_BRANCH}" \
            -- \
            ${VARIANT}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          REPO_NAME: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          PLATFORM: "linux/amd64,linux/arm64"
          IS_MAIN_BRANCH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          VARIANT: "basic"
